baseURL = ''
languageCode = 'en-us'
title = "Rain Andrew's Website"

theme = 'hugo-PaperMod'

[params.homeInfoParams]
Title = "Hello there 👋"
Content = "This is my very own profile website!"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/JotaroKujo0525"
