site_name: Jotaro's Documentation
site_author: JotaroKujo0525
site_description: >-
  The documentation of my discord bots and myself!


theme:
  name: "material"
  logo: "https://raw.githubusercontent.com/JotaroKujo0525/Jotaro-Documentation/main/jotaroogavatar.png"

nav:
    - Home: index.md
    - Dio Brando Documentation: 'dio-brando-documentation/introduction.md'
    - Dio Brando Commands: 'dio-brando-documentation/Commands/commands.md'
    - Jonathan Joestar Documentation: 'jonathan-joestar-docs/introduction.md'
    - Jonathan Joestar Commands: 'jonathan-joestar-docs/commands.md'

    

    
copyright: Copyright &copy; 2021-2022 Jotaro Kujo#0525
